### ISSUE TITLE
sticky toolbar

### ISSUE THREAD

**Issue by jeanvdr** [francescodist/matFortyTwo#22]
if you want the toolbar to be sticky, add this in nav-toolbar.component.scss
mat-toolbar {
    position: sticky;
    top: 0;
    z-index: 1;
}

**Comment by francescodist** [comment]
@jeanvdr I'm going to close this issue for two reasons:
1) It's not an issue, but a solution. If you feel like this would be a good solution to the problem you should open a PR instead.
2) I don't agree with the proposed solution.  I think layout problems should be solved by making the layout more consistent.

Point 2 is just my opinion, so feel free to open a PR with this solution and maybe discuss why you think it's better. In the meantime, if you want to follow the progress on how I think this should be solved, please follow #25
