### ISSUE TITLE
Custom theme colors or apply a material theme

### ISSUE THREAD

**Issue by stefaniaolivares** [francescodist/matFortyTwo#28]
Hi, thanks for your template! It's amazing! 
I would like to be able to apply a dark theme or a default material theme, it's possible?
What should I do to build a custom theme?

Thank you!!

**Comment by francescodist** [comment]
Hi @stefaniaolivares  you raise some really good questions. The template is built upon a custom theme so it's not possible to use the default ones directly. However customising the theme colours to your needs is as simple as changing the values in "src/variables.scss". Try to change the value for `$my-app-primary` to `mat-palette($mat-blue)` and see how the application's primary colour changes accordingly!

As far as dark themes go, at the moment the theme only gets applied as a light theme, so it might be good to have this distinction, thank you! Please let me know if you need any additional info and I will open an issue once I get your response
